### ISSUE TITLE
Appium tutorial Timeout::Error: execution expired

### ISSUE THREAD

**Issue by irivas** [appium/ruby_lib#305]
Hi there, I am running http://appium.io/slate/en/tutorial/android.html?ruby#running-the-test and an error raises 
```
--- projects/ruby_android ‹master* M?› » rake android[test]
Rake appium.txt path is: /Users/israel.rivas/repos/tutorial/projects/ruby_android/appium.txt
bundle exec ruby ./appium/run.rb android "test"
appium.txt path: /Users/israel.rivas/repos/tutorial/projects/ruby_android/appium.txt
Exists? true
Loading /Users/israel.rivas/repos/tutorial/projects/ruby_android/appium.txt
{
          :caps => {
        :"appium-version" => "1.1.0",
            :platformName => "Android",
         :platformVersion => "4.3",
              :deviceName => "Android",
                     :app => "./api.apk",
                    :name => "Ruby Android Tutorial"
    },
    :appium_lib => {
                 :debug => true,
                  :wait => 30,
        :export_session => true,
               :require => [
            [0] "./appium/android/pages",
            [1] "./appium/android/common.rb"
        ]
    }
}
{
          :caps => {
        :"appium-version" => "1.1.0",
            :platformName => "Android",
         :platformVersion => "4.3",
              :deviceName => "Android",
                     :app => "/Users/israel.rivas/repos/tutorial/projects/ruby_android/api.apk",
                    :name => "Ruby Android Tutorial"
    },
    :appium_lib => {
                 :debug => true,
                  :wait => 30,
        :export_session => true,
               :require => [
            [0] "/Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/pages/accessibility.rb",
            [1] "/Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/pages/animation.rb",
            [2] "/Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/pages/home.rb",
            [3] "/Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/common.rb"
        ]
    }
}
Debug is: true
Device is: android
post /session
{
    :desiredCapabilities => {
        :"appium-version" => "1.1.0",
            :platformName => "Android",
         :platformVersion => "4.3",
              :deviceName => "Android",
                     :app => "/Users/israel.rivas/repos/tutorial/projects/ruby_android/api.apk",
                    :name => "Ruby Android Tutorial"
    }
}

...
post /appium/app/complex_find
{
      :args => [
        [0] [
            [0] [
                [0] [
                    [0] 4,
                    [1] "android.widget.TextView"
                ],
                [1] [
                    [0] 29,
                    [1] "Accessibility"
                ]
            ],
            [1] [
                [0] [
                    [0] 4,
                    [1] "android.widget.TextView"
                ],
                [1] [
                    [0] 5,
                    [1] "Accessibility"
                ]
            ],
            [2] [
                [0] [
                    [0] 4,
                    [1] "android.widget.TextView"
                ],
                [1] [
                    [0] 1,
                    [1] "Accessibility"
                ]
            ]
        ]
    ],
    :script => "complex_find"
}

Finished in 30 secs

  1) Error:
spec home, accessibility, and animation#test_0001_spec:
Timeout::Error: execution expired
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/vendor/bundle/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:43:in `sleep'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/vendor/bundle/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:43:in `rescue in block in wait'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/vendor/bundle/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:38:in `block in wait'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/vendor/bundle/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:36:in `wait'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/vendor/bundle/gems/appium_lib-3.0.2/lib/appium_lib/driver.rb:161:in `rescue in block (3 levels) in promote_singleton_appium_methods'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/vendor/bundle/gems/appium_lib-3.0.2/lib/appium_lib/driver.rb:158:in `block (3 levels) in promote_singleton_appium_methods'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/pages/home.rb:32:in `assert'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/pages/home.rb:9:in `accessibility_click'
    /Users/israel.rivas/repos/tutorial/projects/ruby_android/appium/android/specs/test.rb:6:in `block (2 levels) in <top (required)>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
delete
```
Any help?

**Comment by irivas** [comment]
And this is the output from the server
```
...
info: [debug] Responding to client that we did not find a valid resource
info: <-- POST /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa/appium/app/complex_find 404 1.147 ms - 47
info: --> POST /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa/appium/app/complex_find [[[4,"android.widget.TextView"],[29,"Accessibility"]],[[4,"android.widget.TextView"],[5,"Accessibility"]],[[4,"android.widget.TextView"],[1,"Accessibility"]]]
info: [debug] Responding to client that we did not find a valid resource
info: <-- POST /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa/appium/app/complex_find 404 0.985 ms - 47
info: --> POST /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa/appium/app/complex_find [[[4,"android.widget.TextView"],[29,"Accessibility"]],[[4,"android.widget.TextView"],[5,"Accessibility"]],[[4,"android.widget.TextView"],[1,"Accessibility"]]]
info: [debug] Responding to client that we did not find a valid resource
info: <-- POST /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa/appium/app/complex_find 404 1.151 ms - 47
info: --> DELETE /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /Users/israel.rivas/android-sdk-macosx/platform-tools/adb -s emulator-5554 shell "input keyevent 3"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 44.171
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa"}
info: <-- DELETE /wd/hub/session/d55fe2ea-7ced-4c4e-b4b2-6b0490f63dfa 200 8
```

**Comment by bootstraponline** [comment]
The tutorial is probably out of date due to recent appium server changes. The error message means the element wasn't found and then the wait method timed out. Usually updating the locator will solve that.

- https://github.com/appium/tutorial/issues/15
