### ISSUE TITLE
`perform': undefined method `touch_actions' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by soumyaranjanpanda** [appium/ruby_lib#346]
I am using this code to perform swipe:

1. Appium::TouchAction.new.press(x: 166, y: 600).wait(1000).move_to(x: 660, y: 620).release.perform 
2.Appium::TouchAction.new.swipe(:start_x => 166, :start_y => 600, :end_x => 660, :end_y => 620, :duration => 1000).perform 

Both are working fine on arc (appium ruby console) but not working while I am running through the scripts. It is throwing this error:

C:/Ruby200/lib/ruby/gems/2.0.0/gems/appium_lib-.0.0/lib/appium_lib/device/touch_actions.rb:119:in `perform': undefined method `touch_actions' for nil:NilClass (NoMethodError) from swipe.rb:45:in `<main>' 

I am using
1. selenium-webdriver (2.46.2)
2. appium_console (1.0.4)
3. appium_lib (7.0.0)

**Comment by JaniJegoroff** [comment]
Looks like a timing issue for me since it works fine in arc. I think you should wrap method call inside wait:

`wait { Appium::TouchAction.new.swipe(:start_x => 166, :start_y => 600, :end_x => 660, :end_y => 620, :duration => 1000).perform }`

Are you testing on Android or iOS, what's the appium server version?

**Comment by soumyaranjanpanda** [comment]
Hi @JaniJegoroff 
Am using an Android device(5.0.2) and Appium Server version is 1.4.0.0.

I have tried with your suggestion, still am getting the same error.
Below is my code:

```ruby
require 'appium_lib'
require 'selenium-webdriver'

server_url = "http://127.0.0.1:4723/wd/hub/"

capabilities =
{
platformName: 'Android',
platformVersion: '5.1.0',
deviceName:   'Nexus 5',
udid: '192.168.55.101:5555',
appPackage: 'com.android.contacts',
appActivity: '.activities.PeopleActivity',
}
 
@driver = Selenium::WebDriver.for :remote, 
:desired_capabilities => capabilities, 
:url => server_url

wait = Selenium::WebDriver::Wait.new
wait.until{ Appium::TouchAction.new.swipe(:start_x => 166, :start_y => 600, :end_x => 660, :end_y => 620, :duration => 1000).perform }
@driver.quit 
```
Output:
```ruby
C:/Ruby200/lib/ruby/gems/2.0.0/gems/appium_lib-.0.0/lib/appium_lib/device/touch_actions.rb:119:in `perform': undefined method `touch_actions' for nil:NilClass (NoMethodError) from swipe.rb:48:in `block in <main>'	
```

**Comment by JaniJegoroff** [comment]
I modified your code a bit and run a quick test. I don't see any issues when wrapping method call inside `wait` and Appium server completes swipe command successfully.
```
require 'appium_lib'

server_url = "http://127.0.0.1:4723/wd/hub/"

capabilities =
  {
    platformName: 'Android',
    platformVersion: '5.1.0',
    deviceName:   'Nexus 7',
    #udid: '192.168.55.101:5555',
    appPackage: 'com.android.contacts',
    appActivity: '.activities.PeopleActivity',
  }

class MyWorld
  def foo
    wait { Appium::TouchAction.new.swipe(:start_x => 166, :start_y => 600, :end_x => 660, :end_y => 620, :duration => 1000).perform }
  end
end

Appium::Driver.new(caps: capabilities).start_driver
Appium.promote_appium_methods(MyWorld)

MyWorld.new.foo

$driver.driver_quit
```
```
info: --> POST /wd/hub/session/853e6a17-b6c2-432a-bf50-cd258562e8df/timeouts/implicit_wait {"ms":0}
info: [debug] Set Android implicit wait to 0ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"853e6a17-b6c2-432a-bf50-cd258562e8df"}
info: <-- POST /wd/hub/session/853e6a17-b6c2-432a-bf50-cd258562e8df/timeouts/implicit_wait 200 5.099 ms - 76 {"status":0,"value":null,"sessionId":"853e6a17-b6c2-432a-bf50-cd258562e8df"}
info: --> POST /wd/hub/session/853e6a17-b6c2-432a-bf50-cd258562e8df/touch/perform {"actions":[{"action":"press","options":{"x":166,"y":600}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":660,"y":620}},{"action":"release"}]}
info: [debug] Pushing command to appium work queue: ["swipe",{"startX":166,"startY":600,"endX":660,"endY":620,"steps":28}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":166,"startY":600,"endX":660,"endY":620,"steps":28}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1200,1824]
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1200,1824]
info: [debug] [BOOTSTRAP] [debug] Swiping from [x=166.0, y=600.0] to [x=660.0, y=620.0] with steps: 28
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"853e6a17-b6c2-432a-bf50-cd258562e8df"}
info: <-- POST /wd/hub/session/853e6a17-b6c2-432a-bf50-cd258562e8df/touch/perform 200 1971.718 ms - 76 {"status":0,"value":true,"sessionId":"853e6a17-b6c2-432a-bf50-cd258562e8df"}
```

**Comment by soumyaranjanpanda** [comment]
Hey Jani, I tried with your code. It is working perfectly. Thank You so much.

**Comment by JaniJegoroff** [comment]
@soumyaranjanpanda No problem :+1:

**Comment by linhnh123** [comment]
Hi @JaniJegoroff ,
I tried and I'm getting an error "undefined method `device_is_android?'".

**Comment by KazuCocoa** [comment]
@linhnh123 
Could you create a new issue following the pre-filled template?
