### ISSUE TITLE
run tests with Espresso Driver

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#598]
working on : https://github.com/KazuCocoa/ruby_lib/tree/support_espresso

**Comment by KazuCocoa** [comment]
- failed to launch a target activity and had diff for target apk
    - https://gist.github.com/KazuCocoa/297b1272e4fb0373b06cfffb9712a015

```
$ npm list appium-espresso-driver
appium@1.6.6-beta /Users/kazuaki/GitHub/appium
└── appium-espresso-driver@1.0.0-beta.2
```

**Comment by KazuCocoa** [comment]
`appActivity` should be full activity name. I mean `appActivity` should be `io.appium.android.apis.ApiDemos`, not `.ApiDemos`

**Comment by KazuCocoa** [comment]
# failed

> test_type: https://github.com/appium/ruby_lib_core/blob/53c61d46b25e25ba488bb3e065ddec5ee2e6f83c/test/functional/android/patch_test.rb#L40

```
Selenium::WebDriver::Error::UnknownError:         Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 500 - {"message":"Internal error has occurred","reason":"Failed to get key events for string P��k��m��n (i.e. current IME does not understand how to translate the string into key events). As a workaround, you can use replaceText action to set the text directly in the EditText field."}
            UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 500 - {"message":"Internal error has occurred","reason":"Failed to get key events for string P��k��m��n (i.e. current IME does not understand how to translate the string into key events). As a workaround, you can use replaceText action to set the text directly in the EditText field."}
```

> start_activity

After calling the command, proxy error happens.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Can you also attach the server log for the `.type` call?

**Comment by KazuCocoa** [comment]
@mykola-mokhnach Attached server and logcat logs in https://github.com/appium/ruby_lib/issues/598#issuecomment-392232221

**Comment by KazuCocoa** [comment]
## Failed to get `text`
### OK
```ruby
e = @@driver.find_element :accessibility_id, 'App'
e.text
```
```
[HTTP] --> GET /wd/hub/session/770d403d-4cd1-4e7b-a357-8abd8be25db3/element/8154c293-18c1-40e3-be45-6558193f5643/text
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/770d403d-4cd1-4e7b-a357-8abd8be25db3/element/8154c293-18c1-40e3-be45-6558193f5643/text] to [GET http://localhost:8080/session/5d0b41c5-d3ff-4e92-8e95-97dc1b1b40c7/element/8154c293-18c1-40e3-be45-6558193f5643/text] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"bd7a7bc1-0031-4ab5-8edd-c6bb56c5d55b\",\"sessionId\":\"5d0b41c5-d3ff-4e92-8e95-97dc1b1b40c7\",\"status\":0,\"value\":\"App\"}"
[JSONWP Proxy] Replacing sessionId 5d0b41c5-d3ff-4e92-8e95-97dc1b1b40c7 with 770d403d-4cd1-4e7b-a357-8abd8be25db3
[HTTP] <-- GET /wd/hub/session/770d403d-4cd1-4e7b-a357-8abd8be25db3/element/8154c293-18c1-40e3-be45-6558193f5643/text 200 26 ms - 121
```

### Error
- Error case: get text from 
```
# <android.widget.EditText index="0" package="io.appium.android.apis" text="Left is best" class="android.widget.EditText" content-desc="Left is best" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,129][550,255]" resource-id="app:id/left_text_edit"/> is the target

e = @@driver.find_element :id, 'io.appium.android.apis:id/left_text_edit'
e.text
```
```
[HTTP] --> GET /wd/hub/session/db38bc2a-3a26-486e-8046-22994d75d009/element/5418547b-02df-47ca-94da-b397aad43db9/text
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/db38bc2a-3a26-486e-8046-22994d75d009/element/5418547b-02df-47ca-94da-b397aad43db9/text] to [GET http://localhost:8080/session/26cd282c-bcde-478d-b08c-9e2f8ad8c3ca/element/5418547b-02df-47ca-94da-b397aad43db9/text] with body: {}
[W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C]     at doJwpProxy$ (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:456:13)
[W3C]     at tryCatch (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[HTTP] <-- GET /wd/hub/session/db38bc2a-3a26-486e-8046-22994d75d009/element/5418547b-02df-47ca-94da-b397aad43db9/text 500 63 ms - 1267
[HTTP]
```

the page source. 
```
<?xml version="1.0" encoding="UTF-8"?><com.android.internal.policy.DecorView index="0" package="io.appium.android.apis" class="com.android.internal.policy.DecorView" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1794]" resource-id="">
  <android.widget.LinearLayout index="0" package="io.appium.android.apis" class="android.widget.LinearLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1794]" resource-id="">
    <android.view.ViewStub index="0" package="io.appium.android.apis" class="android.view.ViewStub" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][0,0]" resource-id="android:id/action_mode_bar_stub"/>
    <android.widget.FrameLayout index="1" package="io.appium.android.apis" class="android.widget.FrameLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,63][1080,129]" resource-id="android:id/title_container">
      <android.widget.RelativeLayout index="0" package="io.appium.android.apis" class="android.widget.RelativeLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[11,64][1069,125]" resource-id="app:id/screen">
        <android.widget.TextView index="0" package="io.appium.android.apis" text="Left is best" class="android.widget.TextView" content-desc="Left is best" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[11,64][194,115]" resource-id="app:id/left_text"/>
        <android.widget.TextView index="1" package="io.appium.android.apis" text="Right is always right" class="android.widget.TextView" content-desc="Right is always right" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[740,64][1069,115]" resource-id="app:id/right_text"/>
      </android.widget.RelativeLayout>
    </android.widget.FrameLayout>
    <android.widget.FrameLayout index="2" package="io.appium.android.apis" class="android.widget.FrameLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,129][1080,1794]" resource-id="android:id/content">
      <android.widget.LinearLayout index="0" package="io.appium.android.apis" class="android.widget.LinearLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,129][1080,1794]" resource-id="app:id/screen">
        <android.widget.LinearLayout index="0" package="io.appium.android.apis" class="android.widget.LinearLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,129][1080,255]" resource-id="">
          <android.widget.EditText index="0" package="io.appium.android.apis" text="Left is best" class="android.widget.EditText" content-desc="Left is best" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,129][550,255]" resource-id="app:id/left_text_edit"/>
          <android.widget.Button index="1" package="io.appium.android.apis" text="Change Left" class="android.widget.Button" content-desc="Change Left" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[550,129][807,255]" resource-id="app:id/left_text_button"/>
        </android.widget.LinearLayout>
        <android.widget.LinearLayout index="1" package="io.appium.android.apis" class="android.widget.LinearLayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,255][1080,381]" resource-id="">
          <android.widget.EditText index="0" package="io.appium.android.apis" text="Right is always right" class="android.widget.EditText" content-desc="Right is always right" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,255][550,381]" resource-id="app:id/right_text_edit"/>
          <android.widget.Button index="1" package="io.appium.android.apis" text="Change Right" class="android.widget.Button" content-desc="Change Right" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[550,255][827,381]" resource-id="app:id/right_text_button"/>
        </android.widget.LinearLayout>
      </android.widget.LinearLayout>
    </android.widget.FrameLayout>
  </android.widget.LinearLayout>
</com.android.internal.policy.DecorView>
```

----

## broken http response

Sometimes, I got the below error. It was recovered after restarting appium server.

```
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\n\n    <meta name=\"description\" content=\"\">\n    <meta name=\"author\" content=\"\">\n\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\n    <!-- Fav and touch icons -->\n    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\"\n        href=\"./img/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png\">\n    <link rel=\"shortcut icon\" href=\"./favicon.ico\" type=\"image/x-icon\">\n\n    <title>Report Portal - Page 404</title>\n</head>\n<body>\n    <style type=\"text/css\">\n        @font-face {\n            font-family: \"OpenSansRegular\";\n            /*src: local(\"OpenSansRegular\");*/\n            src: local(\"☺\");\n            src: url('compiled/fonts/font-OpenSansRegular/open-sans-regular.eot'),\n                 url('compiled/fonts/font-Ope...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\n\n    <meta name=\"description\" content=\"\">\n    <meta name=\"author\" content=\"\">\n\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\n    <!-- Fav and touch icons -->\n    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\"\n        href=\"./img/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png\">\n    <link rel=\"shortcut icon\" href=\"./favicon.ico\" type=\"image/x-icon\">\n\n    <title>Report Portal - Page 404</title>\n</head>\n<body>\n    <style type=\"text/css\">\n        @font-face {\n            font-family: \"OpenSansRegular\";\n            /*src: local(\"OpenSansRegular\");*/\n            src: local(\"☺\");\n            src: url('compiled/fonts/font-OpenSansRegular/open-sans-regular.eot'),\n                 url('compiled/fonts/font-Ope...
```

**Comment by KazuCocoa** [comment]
Yup. I've added logcat section in the comment. https://gist.github.com/KazuCocoa/a3dfa5bd04fa7510ebda0d835ccb21c8 is the one when `e.text` was called. @mykola-mokhnach

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/issues/598#issuecomment-392298885 crashes in https://github.com/appium/appium-espresso-driver/blob/aee520190a4a8f3706b7189cc0293db788b0f18e/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java#L67

**Comment by mykola-mokhnach** [comment]
such exception is super strange . getText call is never supposed to return a result of type different from CharSequence and here `android.content.res.ColorStateList` instance has been returned.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Can you please try to add debug logs for `appiumResponse.getValue()` and for `matchingRoute` variable inside Router->route method to see what the code is doing?

**Comment by KazuCocoa** [comment]
Yeah... > such exception is super strange

https://gist.github.com/KazuCocoa/c8f8d834438643914d8aa516818305ed is the log which includes https://github.com/appium/ruby_lib/issues/598#issuecomment-393567092 and some additional logs.

And the logcat indicated `gsonBuilder.create().toJson(response)` in the below is the entry point..
```
        return newFixedLengthResponse(response.getHttpStatus(),
                MediaType.APPLICATION_JSON, gsonBuilder.create().toJson(response));
```

The element try to get text is text field of:

![](https://user-images.githubusercontent.com/5511591/40787433-882205c4-6528-11e8-9401-c12d7a08471c.png)

**Comment by KazuCocoa** [comment]
Switched appium-espresso-driver with current master: ccc67c54283604d4be2f2342b6beab941dff5c72

Routing error happened.

- ruby
```
[2] pry(#<AppiumLibCoreTest::DriverTest>)> @@driver.find_element :accessibility_id, 'Content'
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not find :session section for url: /wd/hub/session/4aafecc1-1ca6-4519-bc8c-5f332983f9e6/element
from UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not find :session section for url: /wd/hub/session/4aafecc1-1ca6-4519-bc8c-5f332983f9e6/element
```

- server

```
[HTTP] --> POST /wd/hub/session/4aafecc1-1ca6-4519-bc8c-5f332983f9e6/element
[HTTP] {"using":"accessibility id","value":"Content"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not find :session section for url: /wd/hub/session/4aafecc1-1ca6-4519-bc8c-5f332983f9e6/element
[W3C]     at doJwpProxy$ (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:456:13)
[W3C]     at tryCatch (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Users/kazuaki/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/4aafecc1-1ca6-4519-bc8c-5f332983f9e6/element 500 6 ms - 1311
[HTTP]
```

https://github.com/appium/appium-espresso-driver/blob/9a85f062c3ceed40d77076c14aff3cc60375cb91/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java#L137

But URLs which handled in outside espresso server works like `timeout`.

**Comment by mykola-mokhnach** [comment]
I think this error is related to the recent changes in base driver: 
https://github.com/appium/appium-base-driver/pull/236, since functional tests in other drivers failed as well.

@imurchie FYI

**Comment by KazuCocoa** [comment]
note:

- replace `:uiautomator` related methods with non-uiautomator in test cases

**Comment by KazuCocoa** [comment]
1.0.0

https://gist.github.com/KazuCocoa/11a5329a8489b8c0f98a723d959cb926
`61 tests, 53 assertions, 2 failures, 32 errors, 3 skips`

will take a look at the errors and failures.

**Comment by KazuCocoa** [comment]
I almost ensured existing test cases
