### ISSUE TITLE
no superclass method `text_exact' for RSpec::ExampleGroups

### ISSUE THREAD

**Issue by laiyuncong8404** [appium/ruby_lib#672]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
* no superclass method `text_exact' for RSpec::ExampleGroups if I use Rspec config helper
## Environment
* Appium version (or git revision):
`1.6.5`
* `ruby_lib` version:
`9.6.1`
* Mobile platform/version/device under test:
`iPhone 6, iOS 10.3.1,  iOS Simulator`
## Actual behaviour and steps to reproduce
It works fine by initialize driver with `Appium::Driver.new(opts, true).start_driver`,
but I get a problem, I want to run these spec files together, so I write a spec_helper.rb file like this,
then the error shows`no superclass method `text_exact' for RSpec::ExampleGroups`
```ruby
require 'rspec'
require 'appium_lib'

def setup_driver
	return if $driver
	appium_txt  = File.expand_path(File.join(File.dirname(__FILE__), 'appium.txt'))
	@caps = Appium.load_appium_txt file: appium_txt, verbose: true
	Appium::Driver.new (@caps)
end

def promote_methods
	Appium.promote_appium_methods RSpec::Core::ExampleGroup
end

RSpec.configure do |config|
	config.run_all_when_everything_filtered = true
	config.alias_it_should_behave_like_to :include_shared
	config.before (:suite) do
		setup_driver
		$driver.start_driver
		promote_methods
	end

	config.before (:all) do
		set_wait (120)
	end

	config.after (:suite) do
		$driver.driver_quit
	end
end
```
## Ruby logs
```ruby 
Failure/Error: text_exact('Add Connection').click

  Selenium::WebDriver::Error::UnknownError:
    Method is not implemented
  # ./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
  # ------------------
  # --- Caused by: ---
  # NoMethodError:
  #   super: no superclass method `text_exact' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007fc34c951b10>
  #   Did you mean?  texts_exact
  #   ./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
------------------
--- Caused by: ---
NoMethodError:
  super: no superclass method `text_exact' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007fc34c951b10>
  Did you mean?  texts_exact
  ./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
```

## Appnium logs
```shell
2017-09-28 13:40:12:368 - [Appium] New XCUITestDriver session created successfully, session 06ec3d3a-616f-4f91-a4d6-8a9393ae98fa added to master session list
2017-09-28 13:40:12:377 - [HTTP] <-- POST /wd/hub/session 200 22367 ms - 574
2017-09-28 13:40:12:387 - [HTTP] --> GET /wd/hub/status {}
2017-09-28 13:40:12:457 - [HTTP] <-- GET /wd/hub/status 200 67 ms - 83
2017-09-28 13:40:12:463 - [HTTP] --> POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait {"ms":0}
2017-09-28 13:40:12:537 - [HTTP] <-- POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait 200 74 ms - 76
2017-09-28 13:40:12:542 - [HTTP] --> POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait {"ms":120000}
2017-09-28 13:40:12:563 - [HTTP] <-- POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait 200 17 ms - 76
2017-09-28 13:40:12:566 - [HTTP] --> POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/execute {"script":"        (function() {\n          var opts = {\"typeArray\":[\"UIAStaticText\"],\"onlyVisible\":true,\"name\":{\"target\":\"Add Connection\",\"substring\":false,\"insensitive\":false},\"label\":{\"target\":\"Add Connection\",\"substring\":false,\"insensitive\":false},\"value\":{\"target\":\"Add Connection\",\"substring\":false,\"insensitive\":false},\"onlyFirst\":true};\n          var result = false;\n\n          try {\n            result = $._elementOrElementsByType($.mainWindow(), opts);\n          } catch (e) {\n          }\n\n          return result;\n        })();\n","args":[]}
2017-09-28 13:40:12:603 - [HTTP] <-- POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/execute 501 37 ms - 112
2017-09-28 13:40:12:827 - [HTTP] --> DELETE /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa {}
2017-09-28 13:40:13:209 - [XCUITest] Shutting down sub-processes
2017-09-28 13:40:13:210 - [XCUITest] Shutting down xcodebuild process (pid 6957)
2017-09-28 13:40:13:233 - [XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
2017-09-28 13:40:13:247 - [XCUITest] Setting '755' permissions to '/Users/xiaoxue/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
2017-09-28 13:40:13:253 - [Appium] Removing session 06ec3d3a-616f-4f91-a4d6-8a9393ae98fa from our master session list
2017-09-28 13:40:13:265 - [HTTP] <-- DELETE /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa 200
```

**Comment by laiyuncong8404** [comment]
And I got another odd error this afternoon, even initialize global driver by` Appium::Driver.new(opts, true).start_driver`,  and run rspec file one by one, not in group.
```shell
  pub_topic_iOS (FAILED - 1)

Failures:

  1) MQTT_iOS_Pub pub_topic_iOS
     Failure/Error: swipe(start_x: 200, start_y: 80, end_x: 200, end_y: 400, duration: 2000)

     ArgumentError:
       missing keyword: direction
     # ./iOS_pub_appium+ruby_spec.rb:135:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   super: no superclass method `swipe' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007ffbf33def18>
     #   ./iOS_pub_appium+ruby_spec.rb:135:in `block (2 levels) in <top (required)>'
```
or
```shell
# NoMethodError:
     #   super: no superclass method `scroll' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007fc106be5dd8>
```

**Comment by KazuCocoa** [comment]
- For swipe and scroll

If you use `xcuitest` for automationName, [ios-xctest-mobile-gestures](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) is used for guesture command. And in `ruby_lib` world, https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/ios/xcuitest/command/gestures.rb#L4 is uses instead of [`TouchAction`](https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/core/device/touch_actions.rb)
This behaviour is changed from [v9.4.0](https://github.com/appium/ruby_lib/blob/master/CHANGELOG.md#v940)

**Comment by KazuCocoa** [comment]
How about the following?
If the following works for `text_exact`, `promote_appium_methods` works expected. We should consider `RSpec::Core::ExampleGroup`.

```diff
def promote_methods
-	Appium.promote_appium_methods RSpec::Core::ExampleGroup
+	Appium.promote_appium_methods Object
end
```

**Comment by KazuCocoa** [comment]
@laiyuncong8404 ^

**Comment by laiyuncong8404** [comment]
> How about the following?
If the following works for text_exact, promote_appium_methods works expected. We should consider RSpec::Core::ExampleGroup.
```ruby
def promote_methods
-	Appium.promote_appium_methods RSpec::Core::ExampleGroup
+	Appium.promote_appium_methods Object
end
```
It work fine.

**Comment by laiyuncong8404** [comment]
* For swipe and scroll

**Comment by KazuCocoa** [comment]
🆒  and `Appium.promote_appium_methods` works expectedly. We should consider`RSpec::Core::ExampleGroup`. How about `RSpec` instead of `Object`? It depends on some environment. So, it's better to choose yourself.

Hm...
It seems it depends on WebDriverAgent and simulator's environment.
How about using `scroll(direction: 'down', element: degree_text)` instead?
@laiyuncong8404

**Comment by laiyuncong8404** [comment]
much appreciated.
> How about RSpec instead of Object?

It still don't work either. :confused:

And I tried `scroll(direction: 'down', element: degree_text)` and `scroll(direction: 'down')` both on simulator and real device(iPhone6 10.3.3), the result shows that only `scroll(direction: 'down')` work. 
Maybe you are right, it depends on environment.

**Comment by KazuCocoa** [comment]
BTW, you can probably also use `promote_appium_methods` as the following.
(In this case, we can avoid extending Appium related method to `Object` itself.

```ruby
require 'rspec'
require 'appium_lib'

module Example
    def setup_driver
	return if $driver
	appium_txt  = File.expand_path(File.join(File.dirname(__FILE__), 'appium.txt'))
	@caps = Appium.load_appium_txt file: appium_txt, verbose: true
	Appium::Driver.new (@caps)
        
    def promote_appium_methods
        Appium.promote_appium_methods Example
    end
end

RSpec.configure do |config|
        c.include Example

	config.run_all_when_everything_filtered = true
	config.alias_it_should_behave_like_to :include_shared
	config.before (:suite) do
		setup_driver
		$driver.start_driver
                promote_appium_methods
	end

	config.before (:all) do
		set_wait (120)
	end

	config.after (:suite) do
		$driver.driver_quit
	end
end
```

----

> And I tried scroll(direction: 'down', element: degree_text) and scroll(direction: 'down') both on simulator and real device(iPhone6 10.3.3), the result shows that only scroll(direction: 'down') work.

Could you attach the appium log?
I guess the log help us if we need to take a look at `xcuitest-driver` side code.

-----

Anyway, the problems in this issue are resolved.
I'll close this issue after some conversations for `scroll` related issue.

**Comment by laiyuncong8404** [comment]
## Appium log
```shell
2017-10-09 14:02:49:559 - [JSONWP Proxy] Replacing sessionId D4F8A56D-99AA-490F-AD62-EA5E959FD0FC with 3c72fb20-c56c-48fa-a21c-54fe0e69fc64
2017-10-09 14:02:49:560 - [HTTP] <-- POST /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/element/86B6C33E-A193-4B67-99DF-90951E5D54AB/click 200 850 ms - 118
2017-10-09 14:03:29:569 - [HTTP] --> POST /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/elements {"using":"-ios predicate string","value":"type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")"}
2017-10-09 14:03:30:357 - [HTTP] <-- POST /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/elements 200 788 ms - 179
2017-10-09 14:03:30:361 - [HTTP] --> GET /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/element/AAB1E38F-02B1-4A90-AAC0-6DDB6AE758FB/displayed {}
2017-10-09 14:03:30:361 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2017-10-09 14:03:30:964 - [JSONWP Proxy] Replacing sessionId D4F8A56D-99AA-490F-AD62-EA5E959FD0FC with 3c72fb20-c56c-48fa-a21c-54fe0e69fc64
2017-10-09 14:03:30:965 - [HTTP] <-- GET /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/element/AAB1E38F-02B1-4A90-AAC0-6DDB6AE758FB/displayed 200 604 ms - 76
2017-10-09 14:03:30:968 - [HTTP] --> POST /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/execute {"script":"mobile: scroll","args":[{"direction":"up","element":"AAB1E38F-02B1-4A90-AAC0-6DDB6AE758FB"}]}
2017-10-09 14:03:31:467 - [HTTP] <-- POST /wd/hub/session/3c72fb20-c56c-48fa-a21c-54fe0e69fc64/execute 200 499 ms - 74
2017-10-09 14:04:31:475 - [BaseDriver] Shutting down because we waited 60 seconds for a command
```

**Comment by KazuCocoa** [comment]
Thanks!

It probably looks [WebDriverAgent](https://github.com/facebook/WebDriverAgent) related issue because `appium-xcuitest-driver` didn't get any responses from the driver agent.

Could you get debug logs to get more detail data like `--log-level debug` for appium server? (To unclear if `appium-xcuitest-driver` related or the driver agent related.)

**Comment by laiyuncong8404** [comment]
`swipe(direction:'down')` worked while `scroll(direction:'up', element:degree_text)` don't, but I can't find the difference。
## Appium Logs for  `scroll(direction:'up', element:degree_text)`
```shell
2017-10-10 09:14:51:656 - [HTTP] --> POST /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/elements {"using":"-ios predicate string","value":"type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")"}
2017-10-10 09:14:51:658 - [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["-ios predicate string","type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")","ea63824c-3ed7-4ff3-bb90-817b89b6f43f"]
2017-10-10 09:14:51:658 - [debug] [XCUITest] Executing command 'findElements'
2017-10-10 09:14:51:669 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2017-10-10 09:14:51:670 - [debug] [BaseDriver] Waiting up to 20000 ms for condition
2017-10-10 09:14:51:673 - [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/9B35C0FD-F944-47D8-9585-3DA0509F144F/elements] with body: {"using":"predicate string","value":"type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")"}
2017-10-10 09:14:52:271 - [debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"919CD050-BE60-44E8-9746-A259F14A3229","type":"XCUIElementTypeStaticText","label":"15 Degree"}],"sessionId":"9B35C0FD-F944-47D8-9585-3DA0509F144F","status":0}
2017-10-10 09:14:52:273 - [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"919CD050-BE60-44E8-9746-A259F14A3229","type":"XCUIElementTypeStaticText","label":"15 Degree"}]
2017-10-10 09:14:52:275 - [HTTP] <-- POST /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/elements 200 617 ms - 179
2017-10-10 09:14:52:281 - [HTTP] --> GET /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/element/919CD050-BE60-44E8-9746-A259F14A3229/displayed {}
2017-10-10 09:14:52:281 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2017-10-10 09:14:52:282 - [debug] [XCUITest] Executing command 'proxyReqRes'
2017-10-10 09:14:52:293 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/element/919CD050-BE60-44E8-9746-A259F14A3229/displayed] to [GET http://localhost:8100/session/9B35C0FD-F944-47D8-9585-3DA0509F144F/element/919CD050-BE60-44E8-9746-A259F14A3229/displayed] with body: {}
2017-10-10 09:14:52:657 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"9B35C0FD-F944-47D8-9585-3DA0509F144F\",\n  \"status\" : 0\n}"
2017-10-10 09:14:52:658 - [JSONWP Proxy] Replacing sessionId 9B35C0FD-F944-47D8-9585-3DA0509F144F with ea63824c-3ed7-4ff3-bb90-817b89b6f43f
2017-10-10 09:14:52:659 - [HTTP] <-- GET /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/element/919CD050-BE60-44E8-9746-A259F14A3229/displayed 200 377 ms - 76
2017-10-10 09:14:52:662 - [HTTP] --> POST /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/execute {"script":"mobile: scroll","args":[{"direction":"up","element":"919CD050-BE60-44E8-9746-A259F14A3229"}]}
2017-10-10 09:14:52:663 - [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"up","element":"919CD050-BE60-44E8-9746-A259F14A3229"}],"ea63824c-3ed7-4ff3-bb90-817b89b6f43f"]
2017-10-10 09:14:52:663 - [debug] [XCUITest] Executing command 'execute'
2017-10-10 09:14:52:680 - [debug] [JSONWP Proxy] Proxying [POST /wda/element/919CD050-BE60-44E8-9746-A259F14A3229/scroll] to [POST http://localhost:8100/session/9B35C0FD-F944-47D8-9585-3DA0509F144F/wda/element/919CD050-BE60-44E8-9746-A259F14A3229/scroll] with body: {"direction":"up"}
2017-10-10 09:14:53:033 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"9B35C0FD-F944-47D8-9585-3DA0509F144F","status":0}
2017-10-10 09:14:53:034 - [debug] [MJSONWP] Responding to client with driver.execute() result: {}
2017-10-10 09:14:53:037 - [HTTP] <-- POST /wd/hub/session/ea63824c-3ed7-4ff3-bb90-817b89b6f43f/execute 200 373 ms - 74
2017-10-10 09:15:53:042 - [BaseDriver] Shutting down because we waited 60 seconds for a command
```
## Appium Logs for  `swipe(direction:'down')`
```shell
2017-10-10 09:24:47:073 - [HTTP] --> POST /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/elements {"using":"-ios predicate string","value":"type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")"}
2017-10-10 09:24:47:074 - [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["-ios predicate string","type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")","07459d09-7bb6-40e2-952e-e9814a3c7aeb"]
2017-10-10 09:24:47:074 - [debug] [XCUITest] Executing command 'findElements'
2017-10-10 09:24:47:078 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2017-10-10 09:24:47:078 - [debug] [BaseDriver] Waiting up to 20000 ms for condition
2017-10-10 09:24:47:081 - [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6/elements] with body: {"using":"predicate string","value":"type == \"XCUIElementTypeStaticText\" && (name ==[c] \"15 Degree\" || label ==[c] \"15 Degree\" || value ==[c] \"15 Degree\")"}
2017-10-10 09:24:47:682 - [debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"AF19D9C0-B3AA-450D-8D33-01C3608BA721","type":"XCUIElementTypeStaticText","label":"15 Degree"}],"sessionId":"AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6","status":0}
2017-10-10 09:24:47:684 - [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"AF19D9C0-B3AA-450D-8D33-01C3608BA721","type":"XCUIElementTypeStaticText","label":"15 Degree"}]
2017-10-10 09:24:47:685 - [HTTP] <-- POST /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/elements 200 612 ms - 179
2017-10-10 09:24:47:688 - [HTTP] --> GET /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/element/AF19D9C0-B3AA-450D-8D33-01C3608BA721/displayed {}
2017-10-10 09:24:47:689 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2017-10-10 09:24:47:689 - [debug] [XCUITest] Executing command 'proxyReqRes'
2017-10-10 09:24:47:695 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/element/AF19D9C0-B3AA-450D-8D33-01C3608BA721/displayed] to [GET http://localhost:8100/session/AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6/element/AF19D9C0-B3AA-450D-8D33-01C3608BA721/displayed] with body: {}
2017-10-10 09:24:48:069 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6\",\n  \"status\" : 0\n}"
2017-10-10 09:24:48:070 - [JSONWP Proxy] Replacing sessionId AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6 with 07459d09-7bb6-40e2-952e-e9814a3c7aeb
2017-10-10 09:24:48:070 - [HTTP] <-- GET /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/element/AF19D9C0-B3AA-450D-8D33-01C3608BA721/displayed 200 382 ms - 76
2017-10-10 09:24:48:073 - [HTTP] --> POST /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/execute {"script":"mobile: swipe","args":[{"direction":"down"}]}
2017-10-10 09:24:48:074 - [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: swipe",[{"direction":"down"}],"07459d09-7bb6-40e2-952e-e9814a3c7aeb"]
2017-10-10 09:24:48:074 - [debug] [XCUITest] Executing command 'execute'
2017-10-10 09:24:48:082 - [debug] [BaseDriver] Waiting up to 20000 ms for condition
2017-10-10 09:24:48:085 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
2017-10-10 09:24:48:454 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"21DBD50C-12DB-4FFB-8C24-967790B999C7","type":"XCUIElementTypeApplication","label":"EMQ Toolkit"},"sessionId":"AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6","status":0}
2017-10-10 09:24:48:457 - [debug] [JSONWP Proxy] Proxying [POST /wda/element/21DBD50C-12DB-4FFB-8C24-967790B999C7/swipe] to [POST http://localhost:8100/session/AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6/wda/element/21DBD50C-12DB-4FFB-8C24-967790B999C7/swipe] with body: {"direction":"down"}
2017-10-10 09:24:49:950 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"AC189BE9-D836-40AB-9A9E-0C62BBAAA1B6","status":0}
2017-10-10 09:24:49:951 - [debug] [MJSONWP] Responding to client with driver.execute() result: {}
2017-10-10 09:24:49:954 - [HTTP] <-- POST /wd/hub/session/07459d09-7bb6-40e2-952e-e9814a3c7aeb/execute 200 1879 ms - 74
```

**Comment by KazuCocoa** [comment]
Thanks!
hm... the behaviour is WebDriverAgent side, I suppose as mentioned in https://github.com/appium/ruby_lib/issues/672#issuecomment-333288751 .
We need to create a new issue in the repository. Then, attaching view hierarchy is helpful to investigate the reason.

---

off topic:
https://github.com/appium/appium-xcuitest-driver/blob/f834e2a2de1c5b1bf6763712496d7dcd246e779e/lib/commands/gesture.js#L359
By default, `XCUIElementTypeApplication` is set when scroll something.
