### ISSUE TITLE
List incompatible commands

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#739]
## This is a
* [ ] Bug report
* [ ] Question
* [x] Freature Request

## Summary

from: Confirm commands for W3C actions #733

----

- [x] timeouts
    - https://github.com/jlipps/simple-wd-spec#set-timeouts
- [x] Window related:
    - https://github.com/jlipps/simple-wd-spec
    ```
            set_window_rect: [:post, 'session/:session_id/window/rect'.freeze],
            get_window_rect: [:get, 'session/:session_id/window/rect'.freeze],
    ```
- [x] Activate element
    - `get_active_element: [:get, 'session/:session_id/element/active'.freeze],` <= W3C
- [x] Error handling
    - https://github.com/appium/appium/issues/10075

~~https://gist.github.com/KazuCocoa/3ad2868cf64b7572f28ca0c2442fab55~~

----

- not W3C related
    - pull_folder
    ```
    [HTTP] --> POST /wd/hub/session/cc52ba6b-70ec-4fdf-af31-40b88dd8c660/appium/device/pull_folder {"path":"Library/AddressBook"}
    [debug] [MJSONWP] Calling AppiumDriver.pullFolder() with args: ["Library/AddressBook","cc52ba6b-70ec-4fdf-af31-40b88dd8c660"]
    [debug] [XCUITest] Executing command 'pullFolder'
    [debug] [iOS] Pulling 'Library/AddressBook' from sim
    [debug] [XCUITest] Finding sim-relative file: /Users/kazu/Library/Developer/CoreSimulator/Devices/DED4DBAD-8E5E-4AD6-BDC4-E75CF9AD84D8/data/Library/AddressBook
    [debug] [iOS] Adding /Users/kazu/Library/Developer/CoreSimulator/Devices/DED4DBAD-8E5E-4AD6-BDC4-E75CF9AD84D8/data/Library/AddressBook to an in-memory zip archive
    uncaughtException: Cannot read property 'pipesCount' of undefined
	{"date":"Mon Dec 25 2017 09:27:38 GMT+0900 (JST)","process":{"pid":4149,"uid":501,"gid":20,"cwd":"/Users/kazu/GitHub/appium","execPath":"/Users/kazu/.nodebrew/node/v8.0.0/bin/node","version":"v8.0.0","argv":["/Users/kazu/.nodebrew/node/v8.0.0/bin/node","/Users/kazu/GitHub/appium"],"memoryUsage":{"rss":155316224,"heapTotal":128659456,"heapUsed":116347136,"external":560905}},"os":{"loadavg":[7.4228515625,5.16796875,3.71923828125],"uptime":866298},"trace":[{"column":16,"file":"_stream_readable.js","function":"module.exports.Readable.pipe","line":545,"method":"pipe","native":false},{"column":11,"file":"/Users/kazu/GitHub/appium/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js","function":"module.exports.ZipArchiveOutputStream._smartStream","line":184,"method":"_smartStream","native":false},{"column":20,"file":"/Users/kazu/GitHub/appium/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js","function":"module.exports.ZipArchiveOutputStream._appendStream","line":96,"method":"_appendStream","native":false},{"column":10,"file":"/Users/kazu/GitHub/appium/node_modules/compress-commons/lib/archivers/archive-output-stream.js","function":"module.exports.ArchiveOutputStream.entry","line":88,"method":"entry","native":false},{"column":49,"file":"/Users/kazu/GitHub/appium/node_modules/zip-stream/index.js","function":"module.exports.ZipStream.entry","line":157,"method":"entry","native":false},{"column":15,"file":"/Users/kazu/GitHub/appium/node_modules/archiver/lib/plugins/zip.js","function":"Zip.append","line":53,"method":"append","native":false},{"column":16,"file":"/Users/kazu/GitHub/appium/node_modules/archiver/lib/core.js","function":"Archiver._moduleAppend","line":172,"method":"_moduleAppend","native":false},{"column":8,"file":"/Users/kazu/GitHub/appium/node_modules/archiver/lib/core.js","function":"Archiver._onQueueTask","line":370,"method":"_onQueueTask","native":false},{"column":9,"file":"/Users/kazu/GitHub/appium/node_modules/async/dist/async.js","function":null,"line":4069,"method":null,"native":false},{"column":17,"file":"/Users/kazu/GitHub/appium/node_modules/async/dist/async.js","function":"process","line":2317,"method":null,"native":false},{"column":16,"file":"/Users/kazu/GitHub/appium/node_modules/async/dist/async.js","function":"Immediate._onImmediate","line":66,"method":"_onImmediate","native":false},{"column":20,"file":"timers.js","function":"runCallback","line":800,"method":null,"native":false},{"column":5,"file":"timers.js","function":"tryOnImmediate","line":762,"method":null,"native":false},{"column":5,"file":"timers.js","function":"processImmediate [as _immediateCallback]","line":733,"method":null,"native":false}],"stack":["TypeError: Cannot read property 'pipesCount' of undefined","    at module.exports.Readable.pipe (_stream_readable.js:545:16)","    at module.exports.ZipArchiveOutputStream._smartStream (/Users/kazu/GitHub/appium/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)","    at module.exports.ZipArchiveOutputStream._appendStream (/Users/kazu/GitHub/appium/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)","    at module.exports.ArchiveOutputStream.entry (/Users/kazu/GitHub/appium/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)","    at module.exports.ZipStream.entry (/Users/kazu/GitHub/appium/node_modules/zip-stream/index.js:157:49)","    at Zip.append (/Users/kazu/GitHub/appium/node_modules/archiver/lib/plugins/zip.js:53:15)","    at Archiver._moduleAppend (/Users/kazu/GitHub/appium/node_modules/archiver/lib/core.js:172:16)","    at Archiver._onQueueTask (/Users/kazu/GitHub/appium/node_modules/archiver/lib/core.js:370:8)","    at /Users/kazu/GitHub/appium/node_modules/async/dist/async.js:4069:9","    at process (/Users/kazu/GitHub/appium/node_modules/async/dist/async.js:2317:17)","    at Immediate._onImmediate (/Users/kazu/GitHub/appium/node_modules/async/dist/async.js:66:16)","    at runCallback (timers.js:800:20)","    at tryOnImmediate (timers.js:762:5)","    at processImmediate [as _immediateCallback] (timers.js:733:5)"]}
    ```

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib_core/pull/37/files is mandatory to work W3C bridge fine.

**Comment by KazuCocoa** [comment]
I was able to run test code based on W3C in this repository via Selenium Grid 3.8.1 
https://github.com/KazuCocoa/ruby_lib/tree/fix-test-and-grid

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/pull/326
