### ISSUE TITLE
[v9.8.4] Bug: NameError: uninitialized constant Minitest::VERSION

### ISSUE THREAD

**Issue by tommeier** [appium/ruby_lib#750]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary

Running v9.8.4

```
NameError: uninitialized constant Minitest::VERSION
--
  | /opt/rubies/2.4.2/lib/ruby/gems/2.4.0/gems/appium_lib-9.8.4/lib/appium_lib/driver.rb:17:in `<module:Minitest>'
  | /opt/rubies/2.4.2/lib/ruby/gems/2.4.0/gems/appium_lib-9.8.4/lib/appium_lib/driver.rb:2:in `<top (required)>'
  | /opt/rubies/2.4.2/lib/ruby/gems/2.4.0/gems/appium_lib-9.8.4/lib/appium_lib/appium.rb:8:in `require_relative'
```

**Comment by rockwig** [comment]
Related to this: https://github.com/appium/ruby_lib/issues/747

**Comment by KazuCocoa** [comment]
I've released v9.8.5. Could you try the latest one?
thanks.

**Comment by tommeier** [comment]
Works @KazuCocoa - Good implementation of the fix too 

Thanks! 🎉

**Comment by KazuCocoa** [comment]
Thanks for your checking!
