### ISSUE TITLE
window_size is broken

### ISSUE THREAD

**Issue by rajdeepv** [appium/ruby_lib#802]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
I was trying to upgrade ruby client from '9.6.1' to '9.14.3' and observed that driver.window_size does not work. 

Reason: 
The uiautomator2 server handles wd/hub/session/session_id/window/current/size but the client is making call to /wd/hub/session/session_id/window/rect

## Environment
* Appium version (or git revision): 1.6.5
* `ruby_lib` version: 9.14.3
* Mobile platform/version/device under test: Android

## Actual behaviour and steps to reproduce

selenium_webdriver gem version '3.5.2'
$driver.window_size gives error mentioned in below logs

## Link to Appium/Ruby logs

```
2018-07-12 17:05:12:714 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fd2480c7-a273-4bf8-ad6e-d5d7d2d59c26/window/rect] to [GET http://localhost:36000/wd/hub/session/d3fe8436-a64a-43d4-b450-902060144a16/window/rect] with body: {}
2018-07-12 17:05:12:726 - [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - ""
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:408:13)
    at tryCatch (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
2018-07-12 17:05:12:727 - [HTTP] <-- GET /wd/hub/session/fd2480c7-a273-4bf8-ad6e-d5d7d2d59c26/window/rect 500 14 ms - 180
```
Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
It looks the Ruby client works as W3C protocol.
Could you attach full Appium server side log?

I'm wondering the ruby client handles the session as W3C protocol by old Appium's response.

**Comment by rajdeepv** [comment]
@KazuCocoa here are full logs
```
Starting Appium
2018-07-13 09:18:04:812 - [Appium] Welcome to Appium v1.6.5 (REV 60d81fb6fb597b6e415f3d5e6ec933b446cd560a)
2018-07-13 09:18:04:815 - [Appium] Non-default server args:
2018-07-13 09:18:04:816 - [Appium]   sessionOverride: true
2018-07-13 09:18:04:816 - [Appium]   logTimestamp: true
2018-07-13 09:18:04:816 - [Appium]   debugLogSpacing: true
2018-07-13 09:18:04:851 - [Appium] Appium REST http interface listener started on 0.0.0.0:4723


2018-07-13 09:18:34:719 - [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","deviceName":"emulator-5554","platformVersion":null,"app":"./artifacts/bumble.apk","adbPort":5037,"remoteAdbHost":"localhost","appActivity":".ui.launcher.DebugLauncherActivity","appWaitActivity":"*","automationName":"uiautomator2","noSign":true,"newCommandTimeout":600,"chromeOptions":{"androidPackage":"com.bumble.app"},"skipUnlock":true,"noReset":true,"fullReset":false,"systemPort":36000,"optionalIntentArguments":"--es qalink:hotpanel_test_id CAL_101817_615378000false"},"capabilities":{"alwaysMatch":{"platformName":"Android","appium:deviceName":"emulator-5554","appium:app":"./artifacts/bumble.apk","appium:adbPort":5037,"appium:remoteAdbHost":"localhost","appium:appActivity":".ui.launcher.DebugLauncherActivity","appium:appWaitActivity":"*","appium:automationName":"uiautomator2","appium:noSign":true,"appium:newCommandTimeout":600,"appium:chromeOptions":{"androidPackage":"com.bumble.app"},"appium:skipUnlock":true,"appium:noReset":true,"appi
2018-07-13 09:18:34:723 - [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","deviceName":"emulator-5554","platformVersion":null,"app":"./artifacts/bumble.apk","adbPort":5037,"remoteAdbHost":"localhost","appActivity":".ui.launcher.DebugLauncherActivity","appWaitActivity":"*","automationName":"uiautomator2","noSign":true,"newCommandTimeout":600,"chromeOptions":{"androidPackage":"com.bumble.app"},"skipUnlock":true,"noReset":true,"fullReset":false,"systemPort":36000,"optionalIntentArguments":"--es qalink:hotpanel_test_id CAL_101817_615378000false"},null,{"alwaysMatch":{"platformName":"Android","appium:deviceName":"emulator-5554","appium:app":"./artifacts/bumble.apk","appium:adbPort":5037,"appium:remoteAdbHost":"localhost","appium:appActivity":".ui.launcher.DebugLauncherActivity","appium:appWaitActivity":"*","appium:automationName":"uiautomator2","appium:noSign":true,"appium:newCommandTimeout":600,"appium:chromeOptions":{"androidPackage":"com.bumble.app"},"appium:skipUnlock":true,"appium:noReset":true,"appium:fullReset":false,"appium:systemPort":36000,"appium...
2018-07-13 09:18:34:727 - [debug] [BaseDriver] Event 'newSessionRequested' logged at 1531473514726 (10:18:34 GMT+0100 (BST))
2018-07-13 09:18:34:734 - [Appium] Creating new AndroidUiautomator2Driver (v0.11.0) session
2018-07-13 09:18:34:734 - [Appium] Capabilities:
2018-07-13 09:18:34:737 - [Appium]   platformName: 'Android'
2018-07-13 09:18:34:737 - [Appium]   deviceName: 'emulator-5554'
2018-07-13 09:18:34:737 - [Appium]   platformVersion: null
2018-07-13 09:18:34:738 - [Appium]   app: './artifacts/bumble.apk'
2018-07-13 09:18:34:738 - [Appium]   adbPort: 5037
2018-07-13 09:18:34:738 - [Appium]   remoteAdbHost: 'localhost'
2018-07-13 09:18:34:738 - [Appium]   appActivity: '.ui.launcher.DebugLauncherActivity'
2018-07-13 09:18:34:739 - [Appium]   appWaitActivity: '*'
2018-07-13 09:18:34:739 - [Appium]   automationName: 'uiautomator2'
2018-07-13 09:18:34:739 - [Appium]   noSign: true
2018-07-13 09:18:34:739 - [Appium]   newCommandTimeout: 600
2018-07-13 09:18:34:740 - [Appium]   chromeOptions: { androidPackage: 'com.bumble.app' }
2018-07-13 09:18:34:740 - [Appium]   skipUnlock: true
2018-07-13 09:18:34:740 - [Appium]   noReset: true
2018-07-13 09:18:34:743 - [Appium]   fullReset: false
2018-07-13 09:18:34:745 - [Appium]   systemPort: 36000
2018-07-13 09:18:34:745 - [Appium]   optionalIntentArguments: '--es qalink:hotpanel_test_id CAL_101817_615378000false'
2018-07-13 09:18:34:760 - [BaseDriver] The following capabilities were provided, but are not recognized by appium: chromeOptions.
2018-07-13 09:18:34:767 - [BaseDriver] Session created with session id: 8e7a1b07-1a94-4ec8-9786-755e3e479a18
2018-07-13 09:18:34:878 - [BaseDriver] Using local app './artifacts/bumble.apk'
2018-07-13 09:18:34:879 - [debug] [UiAutomator2] Checking whether app is actually present
2018-07-13 09:18:34:882 - [debug] [AndroidDriver] Getting Java version
2018-07-13 09:18:35:340 - [AndroidDriver] Java version is: 1.8.0_151
2018-07-13 09:18:35:351 - [ADB] Checking whether adb is present
2018-07-13 09:18:35:362 - [ADB] Using adb from /Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb
2018-07-13 09:18:35:363 - [AndroidDriver] Retrieving device list
2018-07-13 09:18:35:364 - [debug] [ADB] Trying to find a connected android device
2018-07-13 09:18:35:366 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:35:385 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:35:385 - [AndroidDriver] Using device: emulator-5554
2018-07-13 09:18:35:389 - [ADB] Checking whether adb is present
2018-07-13 09:18:35:390 - [debug] [ADB] Setting device id to emulator-5554
2018-07-13 09:18:35:393 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:35:417 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:35:419 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.sdk"]
2018-07-13 09:18:35:445 - [debug] [ADB] Current device property 'ro.build.version.sdk': 23
2018-07-13 09:18:35:446 - [debug] [ADB] Device API level: 23
2018-07-13 09:18:35:447 - [debug] [AndroidDriver] Parsing package and activity from app manifest
2018-07-13 09:18:35:448 - [ADB] Checking whether aapt is present
2018-07-13 09:18:35:451 - [ADB] Using aapt from /Users/rajdeepvarma/Library/Android/sdk/build-tools/28.0.0/aapt
2018-07-13 09:18:35:452 - [ADB] Extracting package and launch activity from manifest
2018-07-13 09:18:35:513 - [debug] [ADB] badging package: com.bumble.app
2018-07-13 09:18:35:514 - [debug] [ADB] badging act: com.bumble.app.ui.launcher.BumbleLauncherActivity
2018-07-13 09:18:35:514 - [debug] [AndroidDriver] Parsed package and activity are: com.bumble.app/com.bumble.app.ui.launcher.BumbleLauncherActivity
2018-07-13 09:18:35:516 - [ADB] Getting device platform version
2018-07-13 09:18:35:516 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:35:533 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:35:535 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
2018-07-13 09:18:35:587 - [debug] [ADB] Current device property 'ro.build.version.release': 6.0
2018-07-13 09:18:35:589 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:35:604 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:35:605 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","wm","size"]
2018-07-13 09:18:36:100 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:36:112 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:36:113 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","wm","density"]
2018-07-13 09:18:36:546 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:36:555 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:36:555 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","getprop","ro.product.model"]
2018-07-13 09:18:36:575 - [debug] [ADB] Current device property 'ro.product.model': Android SDK built for x86
2018-07-13 09:18:36:576 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:36:589 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:36:589 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","getprop","ro.product.manufacturer"]
2018-07-13 09:18:36:614 - [debug] [ADB] Current device property 'ro.product.manufacturer': unknown
2018-07-13 09:18:36:617 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:36:629 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:36:630 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.uiautomator2.server"]
2018-07-13 09:18:37:113 - [ADB] Checking whether aapt is present
2018-07-13 09:18:37:135 - [debug] [ADB] Getting install status for io.appium.uiautomator2.server
2018-07-13 09:18:37:135 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:37:146 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:37:146 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.uiautomator2.server"]
2018-07-13 09:18:37:405 - [debug] [ADB] App is installed
2018-07-13 09:18:37:405 - [debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
2018-07-13 09:18:37:406 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:37:415 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:37:415 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
2018-07-13 09:18:37:654 - [debug] [ADB] App is installed
2018-07-13 09:18:37:655 - [debug] [ADB] Getting package info for io.appium.uiautomator2.server
2018-07-13 09:18:37:655 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:37:664 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:37:665 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.uiautomator2.server"]
2018-07-13 09:18:37:692 - [debug] [UiAutomator2] Waiting up to 20000ms for instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' to be available
2018-07-13 09:18:37:694 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:37:704 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:37:705 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","list","instrumentation"]
2018-07-13 09:18:37:925 - [debug] [UiAutomator2] Instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' available
2018-07-13 09:18:37:926 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","wait-for-device"]
2018-07-13 09:18:37:937 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:37:946 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:37:947 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","echo","ping"]
2018-07-13 09:18:37:967 - [AndroidDriver] setDeviceLanguageCountry requires language or country.
2018-07-13 09:18:37:968 - [AndroidDriver] Got language: 'null' and country: 'null'
2018-07-13 09:18:37:970 - [debug] [Logcat] Starting logcat capture
2018-07-13 09:18:38:019 - [debug] [AndroidDriver] Pushing settings apk to device...
2018-07-13 09:18:38:022 - [debug] [ADB] Getting install status for io.appium.settings
2018-07-13 09:18:38:023 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:38:038 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:38:039 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.settings"]
2018-07-13 09:18:38:302 - [debug] [ADB] App is installed
2018-07-13 09:18:38:303 - [debug] [ADB] Getting package info for io.appium.settings
2018-07-13 09:18:38:303 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:38:313 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:38:313 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.settings"]
2018-07-13 09:18:38:346 - [ADB] Checking whether aapt is present
2018-07-13 09:18:38:360 - [debug] [ADB] The installed 'io.appium.settings' package does not require upgrade (5 >= 5)
2018-07-13 09:18:38:361 - [debug] [ADB] Device API level: 23
2018-07-13 09:18:38:362 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:38:371 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:38:372 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.settings"]
2018-07-13 09:18:38:395 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:38:414 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:38:415 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","dump","io.appium.settings"]
2018-07-13 09:18:38:730 - [debug] [ADB] Got the following command chunks to execute: pm,grant,io.appium.settings,android.permission.CHANGE_NETWORK_STATE,;,pm,grant,io.appium.settings,android.permission.WRITE_SETTINGS,;,pm,grant,io.appium.settings,android.permission.ACCESS_MOCK_LOCATION,;
2018-07-13 09:18:38:731 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:38:739 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:38:740 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","grant","io.appium.settings","android.permission.CHANGE_NETWORK_STATE",";","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
2018-07-13 09:18:39:474 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:39:484 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:39:484 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","ps"]
2018-07-13 09:18:39:516 - [debug] [ADB] Device API level: 23
2018-07-13 09:18:39:516 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:39:527 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:39:527 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","appops","set","io.appium.settings","android:mock_location","allow"]
2018-07-13 09:18:40:012 - [debug] [AndroidDriver] Pushing unlock helper app to device...
2018-07-13 09:18:40:013 - [debug] [ADB] Getting install status for io.appium.unlock
2018-07-13 09:18:40:013 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:40:023 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:40:023 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.unlock"]
2018-07-13 09:18:40:254 - [debug] [ADB] App is installed
2018-07-13 09:18:40:254 - [debug] [ADB] Getting package info for io.appium.unlock
2018-07-13 09:18:40:255 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:40:263 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:40:264 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.unlock"]
2018-07-13 09:18:40:285 - [ADB] Checking whether aapt is present
2018-07-13 09:18:40:300 - [debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade (2 >= 2)
2018-07-13 09:18:40:301 - [debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 36000
2018-07-13 09:18:40:303 - [debug] [ADB] Forwarding system: 36000 to device: 6790
2018-07-13 09:18:40:305 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","forward","tcp:36000","tcp:6790"]
2018-07-13 09:18:40:317 - [debug] [UiAutomator2] 'skipUnlock' capability set, so skipping device unlock
2018-07-13 09:18:40:321 - [debug] [AndroidDriver] Extracting strings from apk ./artifacts/bumble.apk null /var/folders/b4/_133qmmj5k10nsh07rlw4sxw0000gn/T/com.bumble.app
2018-07-13 09:18:40:322 - [debug] [ADB] Extracting strings for language: default
2018-07-13 09:18:40:323 - [debug] [ADB] Device API level: 23
2018-07-13 09:18:40:323 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:40:339 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:40:339 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","getprop","persist.sys.locale"]
2018-07-13 09:18:40:383 - [debug] [ADB] Current device property 'persist.sys.locale': en-GB
2018-07-13 09:18:41:568 - [debug] [ADB] No strings.xml for language 'en', getting default strings.xml
2018-07-13 09:18:42:488 - [AndroidDriver] Could not get strings, continuing anyway
2018-07-13 09:18:42:488 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:42:497 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:42:497 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","echo"]
2018-07-13 09:18:42:694 - [AndroidDriver] Remote apk path is /data/local/tmp/79abe88a66a7982e1b4aae3a12e6b62e.apk
2018-07-13 09:18:42:695 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:42:715 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:42:716 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","ls","/data/local/tmp/79abe88a66a7982e1b4aae3a12e6b62e.apk"]
2018-07-13 09:18:42:743 - [debug] [AndroidDriver] Checking if app is installed
2018-07-13 09:18:42:743 - [debug] [ADB] Getting install status for com.bumble.app
2018-07-13 09:18:42:743 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:42:763 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:42:765 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.bumble.app"]
2018-07-13 09:18:43:014 - [debug] [ADB] App is installed
2018-07-13 09:18:43:015 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:43:024 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:43:024 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.uiautomator2.server"]
2018-07-13 09:18:43:472 - [UiAutomator2] Starting uiautomator2 server v0.3.0
2018-07-13 09:18:43:473 - [UiAutomator2] Running command: 'adb -s emulator-5554 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
2018-07-13 09:18:43:479 - [UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
2018-07-13 09:18:43:482 - [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:36000/wd/hub/status] with no body
2018-07-13 09:18:44:530 - [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:36000/wd/hub/status] with no body
2018-07-13 09:18:45:538 - [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:36000/wd/hub/status] with no body
2018-07-13 09:18:46:546 - [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:36000/wd/hub/status] with no body
2018-07-13 09:18:46:560 - [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"SESSIONID\",\"status\":0,\"value\":\"Status Invoked\"}"
2018-07-13 09:18:46:561 - [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:36000/wd/hub/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","deviceName":"emulator-5554","platformVersion":null,"app":"./artifacts/bumble.apk","adbPort":5037,"remoteAdbHost":"localhost","appActivity":".ui.launcher.DebugLauncherActivity","appWaitActivity":"*","automationName":"uiautomator2","noSign":true,"newCommandTimeout":600,"chromeOptions":{"androidPackage":"com.bumble.app"},"skipUnlock":true,"noReset":true,"fullReset":false,"systemPort":36000,"optionalIntentArguments":"--es qalink:hotpanel_test_id CAL_101817_615378000false"},"platformName":"Android","deviceName":"emulator-5554","platformVersion":"6.0","app":"./artifacts/bumble.apk","adbPort":5037,"remoteAdbHost":"localhost","appActivity":".ui.launcher.DebugLauncherActivity","appWaitActivity":"*","automationName":"uiautomator2","noSign":true,"newCommandTimeout":6...
2018-07-13 09:18:46:572 - [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"976a1ccf-dda1-4201-abaf-a61736aa258e","status":0,"value":"Created Session"}
2018-07-13 09:18:46:573 - [UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.bumble.app/*'. Starting it ourselves
2018-07-13 09:18:46:574 - [debug] [ADB] Device API level: 23
2018-07-13 09:18:46:575 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:46:586 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:46:589 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","com.bumble.app/.ui.launcher.DebugLauncherActivity","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000","--es","qalink:hotpanel_test_id","CAL_101817_615378000false"]
2018-07-13 09:18:47:580 - [debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.bumble.app' and activity: '*' to be focused
2018-07-13 09:18:47:580 - [debug] [ADB] Possible activities, to be checked: '*'
2018-07-13 09:18:47:582 - [debug] [ADB] Getting focused package and activity
2018-07-13 09:18:47:582 - [debug] [ADB] Getting connected devices...
2018-07-13 09:18:47:604 - [debug] [ADB] 1 device(s) connected
2018-07-13 09:18:47:605 - [debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb' with args: ["-H","localhost","-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
2018-07-13 09:18:47:698 - [debug] [ADB] Found package: 'com.bumble.app' and fully qualified activity name : 'com.bumble.app.ui.launcher.DebugLauncherActivity'
2018-07-13 09:18:47:721 - [Appium] New AndroidUiautomator2Driver session created successfully, session 8e7a1b07-1a94-4ec8-9786-755e3e479a18 added to master session list
2018-07-13 09:18:47:731 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1531473527731 (10:18:47 GMT+0100 (BST))
2018-07-13 09:18:47:739 - [debug] [MJSONWP] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"Android","deviceName":"emulator-5554","platformVersion":null,"app":"./artifacts/bumble.apk","adbPort":5037,"remoteAdbHost":"localhost","appActivity":".ui.launcher.DebugLauncherActivity","appWaitActivity":"*","automationName":"uiautomator2","noSign":true,"newCommandTimeout":600,"chromeOptions":{"androidPackage":"com.bumble.app"},"skipUnlock":true,"noReset":true,"fullReset":false,"systemPort":36000,"optionalIntentArguments":"--es qalink:hotpanel_test_id CAL_101817_615378000false"}}
2018-07-13 09:18:47:754 - [HTTP] <-- POST /wd/hub/session 200 13030 ms - 578
2018-07-13 09:18:47:765 - [HTTP] --> POST /wd/hub/session/8e7a1b07-1a94-4ec8-9786-755e3e479a18/timeouts {"implicit":20000}
2018-07-13 09:18:47:782 - [HTTP] <-- POST /wd/hub/session/8e7a1b07-1a94-4ec8-9786-755e3e479a18/timeouts 400 12 ms - 89
2018-07-13 09:18:47:794 - [HTTP] --> GET /wd/hub/status {}
2018-07-13 09:18:47:796 - [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2018-07-13 09:18:47:833 - [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":"60d81fb6fb597b6e415f3d5e6ec933b446cd560a"}}
2018-07-13 09:18:47:842 - [HTTP] <-- GET /wd/hub/status 200 42 ms - 110


2018-07-13 09:18:58:290 - [HTTP] --> GET /wd/hub/session/8e7a1b07-1a94-4ec8-9786-755e3e479a18/window/rect {}
2018-07-13 09:18:58:297 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-07-13 09:18:58:299 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/8e7a1b07-1a94-4ec8-9786-755e3e479a18/window/rect] to [GET http://localhost:36000/wd/hub/session/976a1ccf-dda1-4201-abaf-a61736aa258e/window/rect] with body: {}
2018-07-13 09:18:58:354 - [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - ""
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:408:13)
    at tryCatch (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/rajdeepvarma/bma-calabash/bumble/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
2018-07-13 09:18:58:356 - [HTTP] <-- GET /wd/hub/session/8e7a1b07-1a94-4ec8-9786-755e3e479a18/window/rect 500 66 ms - 180

```

**Comment by mykola-mokhnach** [comment]
Appium 1.6.5 is out of date. Update to the most recent one and try again

**Comment by mykola-mokhnach** [comment]
@rajdeepv Protocol translation happens in https://github.com/appium/appium-base-driver
