### ISSUE TITLE
ruby_lib × Appium Desktop. Appium Desktop crashes.

### ISSUE THREAD

**Issue by aha-oretama** [appium/ruby_lib#821]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
When a test stops for debugging (pry, IDE ...) and select elements in Appium Desktop, then Appium Desktop crashes.

Do following steps to reproduce.

0. Appium server starts by Appium Desktop
1. Run and stop a test by using a debugging tool
2. Start inspector session and attach the session
3. Then you can see App source and app's ui in Appium Desktop
4. Choose 'Select Elements' and touch app ui through Appium Desktop
5. Normally, select the element. But Appium Desktop crashes and disappears

I just found out the condition whether Appium Desktop craches or not.
By adding `forceMjsonwp = true` in desired capabilities, Appium Desktop will not crash.

I think that this issue is for ruby_lib because whether Appium Desktop crashes or not is depends on ruby_lib's capability. So I create an issue in this repository.
If this issue is because of Appium Desktop, please change this issue to Appium Desktop repository.

## Environment
* Appium version (or git revision): 1.9.0
* `ruby_lib` version: 2.5.1p57 
* Appium Desktop: 1.7.0
* Mobile platform/version/device under test: I used some emulators such as Nexus 5X API 26.

## Link to Appium/Ruby logs
Appium Desktop's logs. This is gotton by running Appium Desktop's master branch app by `npm run dev`.
```
[1] [debug] [W3C] Calling AppiumDriver.findElements() with args: ["accessibility id","Access'ibility","12854801-89bc-4a47-8dbc-15e7b9e6e4b0"]
[1] [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[1] [debug] [BaseDriver] Waiting up to 1000 ms for condition
[1] [debug] [JSONWP Proxy] Matched '/elements' to command name 'findElements'
[1] [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/772fb6b1-f8f9-4523-97ea-64f523afbf85/elements] with body: {"strategy":"accessibility id","selector":"Access'ibility","context":"","multiple":true}
[1] [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"772fb6b1-f8f9-4523-97ea-64f523afbf85","status":0,"value":[{"ELEMENT":"b7a5b237-66eb-49e3-a901-fcc03b9ff293"}]}
[1] [debug] [W3C] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"b7a5b237-66eb-49e3-a901-fcc03b9ff293"}]
[1] [HTTP] <-- POST /wd/hub/session/12854801-89bc-4a47-8dbc-15e7b9e6e4b0/elements 200 95 ms - 90
[1] [HTTP] 
[1] uncaughtException: no value passed to Element constructor
[1] 	{"date":"Tue Sep 25 2018 21:19:28 GMT+0900 (JST)","process":{"pid":1116,"uid":502,"gid":20,"cwd":"/Users/aha-oretama/IdeaProjects/appium-desktop","execPath":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron","version":"v8.9.3","argv":["/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron","-r","./node_modules/babel-register","-r","./node_modules/babel-polyfill","--inspect=5858","./app/main/main.development","--color"],"memoryUsage":{"rss":266121216,"heapTotal":223625216,"heapUsed":200562112,"external":1320230}},"os":{"loadavg":[4.24853515625,3.54248046875,3.50537109375],"uptime":39408},"trace":[{"column":11,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/element.js","function":"PromiseElement.Element","line":15,"method":"Element","native":false},{"column":20,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js","function":"new PromiseElement","line":73,"method":null,"native":false},{"column":12,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js","function":"PromiseWebdriver.newElement","line":103,"method":"newElement","native":false},{"column":24,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js","function":null,"line":137,"method":null,"native":false},{"column":7,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js","function":null,"line":82,"method":null,"native":false},{"column":5,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/webdriver.js","function":null,"line":179,"method":null,"native":false},{"column":7,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/http-utils.js","function":"Request._callback","line":89,"method":"_callback","native":false},{"column":22,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js","function":"Request.self.callback","line":186,"method":"callback","native":false},{"column":13,"file":"events.js","function":"emitTwo","line":126,"method":null,"native":false},{"column":7,"file":"events.js","function":"Request.emit","line":214,"method":"emit","native":false},{"column":10,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js","function":null,"line":1163,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"file":"events.js","function":"Request.emit","line":211,"method":"emit","native":false},{"column":12,"file":"/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js","function":null,"line":1085,"method":null,"native":false},{"column":30,"file":"events.js","function":"Object.onceWrapper","line":313,"method":"onceWrapper","native":false},{"column":20,"file":"events.js","function":"emitNone","line":111,"method":null,"native":false},{"column":7,"file":"events.js","function":"IncomingMessage.emit","line":208,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"endReadableNT","line":1056,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":138,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":180,"method":"_tickCallback","native":false}],"stack":["Error: no value passed to Element constructor","    at PromiseElement.Element (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/element.js:15:11)","    at new PromiseElement (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js:73:20)","    at PromiseWebdriver.newElement (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js:103:12)","    at /Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js:137:24","    at /Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js:82:7","    at /Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/webdriver.js:179:5","    at Request._callback (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/http-utils.js:89:7)","    at Request.self.callback (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js:186:22)","    at emitTwo (events.js:126:13)","    at Request.emit (events.js:214:7)","    at Request.<anonymous> (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js:1163:10)","    at emitOne (events.js:116:13)","    at Request.emit (events.js:211:7)","    at IncomingMessage.<anonymous> (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js:1085:12)","    at Object.onceWrapper (events.js:313:30)","    at emitNone (events.js:111:20)","    at IncomingMessage.emit (events.js:208:7)","    at endReadableNT (_stream_readable.js:1056:12)","    at _combinedTickCallback (internal/process/next_tick.js:138:11)","    at process._tickCallback (internal/process/next_tick.js:180:9)"]}
```

## Any additional comments

I just do above steps to reproduce by using forked https://github.com/aha-oretama/ruby_lib/tree/for-integration-appium-desktop/android_tests.
I just used `binding.pry` method in a that time.

**Comment by KazuCocoa** [comment]
`forceMjsonwp = true` only affects which protocol follows, MJSONWP or W3C.
If the error happens with W3C, it probably happens other clients as well.

Did the error happen with appium CLI? I anticipate it is because of appium desktop.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/issues/568

**Comment by KazuCocoa** [comment]
```
{
  "date": "Tue Sep 25 2018 21:19:28 GMT+0900 (JST)",
  "process": {
    "pid": 1116,
    "uid": 502,
    "gid": 20,
    "cwd": "/Users/aha-oretama/IdeaProjects/appium-desktop",
    "execPath": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron",
    "version": "v8.9.3",
    "argv": [
      "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron",
      "-r",
      "./node_modules/babel-register",
      "-r",
      "./node_modules/babel-polyfill",
      "--inspect=5858",
      "./app/main/main.development",
      "--color"
    ],
    "memoryUsage": {
      "rss": 266121216,
      "heapTotal": 223625216,
      "heapUsed": 200562112,
      "external": 1320230
    }
  },
  "os": {
    "loadavg": [
      4.24853515625,
      3.54248046875,
      3.50537109375
    ],
    "uptime": 39408
  },
  "trace": [
    {
      "column": 11,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/element.js",
      "function": "PromiseElement.Element",
      "line": 15,
      "method": "Element",
      "native": false
    },
    {
      "column": 20,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js",
      "function": "new PromiseElement",
      "line": 73,
      "method": null,
      "native": false
    },
    {
      "column": 12,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js",
      "function": "PromiseWebdriver.newElement",
      "line": 103,
      "method": "newElement",
      "native": false
    },
    {
      "column": 24,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js",
      "function": null,
      "line": 137,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js",
      "function": null,
      "line": 82,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/webdriver.js",
      "function": null,
      "line": 179,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/http-utils.js",
      "function": "Request._callback",
      "line": 89,
      "method": "_callback",
      "native": false
    },
    {
      "column": 22,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js",
      "function": "Request.self.callback",
      "line": 186,
      "method": "callback",
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitTwo",
      "line": 126,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "Request.emit",
      "line": 214,
      "method": "emit",
      "native": false
    },
    {
      "column": 10,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js",
      "function": null,
      "line": 1163,
      "method": null,
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitOne",
      "line": 116,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "Request.emit",
      "line": 211,
      "method": "emit",
      "native": false
    },
    {
      "column": 12,
      "file": "/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js",
      "function": null,
      "line": 1085,
      "method": null,
      "native": false
    },
    {
      "column": 30,
      "file": "events.js",
      "function": "Object.onceWrapper",
      "line": 313,
      "method": "onceWrapper",
      "native": false
    },
    {
      "column": 20,
      "file": "events.js",
      "function": "emitNone",
      "line": 111,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "IncomingMessage.emit",
      "line": 208,
      "method": "emit",
      "native": false
    },
    {
      "column": 12,
      "file": "_stream_readable.js",
      "function": "endReadableNT",
      "line": 1056,
      "method": null,
      "native": false
    },
    {
      "column": 11,
      "file": "internal/process/next_tick.js",
      "function": "_combinedTickCallback",
      "line": 138,
      "method": null,
      "native": false
    },
    {
      "column": 9,
      "file": "internal/process/next_tick.js",
      "function": "process._tickCallback",
      "line": 180,
      "method": "_tickCallback",
      "native": false
    }
  ],
  "stack": [
    "Error: no value passed to Element constructor",
    "    at PromiseElement.Element (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/element.js:15:11)",
    "    at new PromiseElement (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js:73:20)",
    "    at PromiseWebdriver.newElement (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/promise-webdriver.js:103:12)",
    "    at /Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js:137:24",
    "    at /Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/callbacks.js:82:7",
    "    at /Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/webdriver.js:179:5",
    "    at Request._callback (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/wd/lib/http-utils.js:89:7)",
    "    at Request.self.callback (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js:186:22)",
    "    at emitTwo (events.js:126:13)",
    "    at Request.emit (events.js:214:7)",
    "    at Request.<anonymous> (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js:1163:10)",
    "    at emitOne (events.js:116:13)",
    "    at Request.emit (events.js:211:7)",
    "    at IncomingMessage.<anonymous> (/Users/aha-oretama/IdeaProjects/appium-desktop/node_modules/request/request.js:1085:12)",
    "    at Object.onceWrapper (events.js:313:30)",
    "    at emitNone (events.js:111:20)",
    "    at IncomingMessage.emit (events.js:208:7)",
    "    at endReadableNT (_stream_readable.js:1056:12)",
    "    at _combinedTickCallback (internal/process/next_tick.js:138:11)",
    "    at process._tickCallback (internal/process/next_tick.js:180:9)"
  ]
}
```

**Comment by KazuCocoa** [comment]
@aha-oretama 
Could you share the desktop log before the crash?

**Comment by aha-oretama** [comment]
@KazuCocoa 
I share the desktop log. It record from desktop's start to finish by crash.
https://gist.github.com/aha-oretama/d3f33915a425643b937d270d01cb68a9

**Comment by aha-oretama** [comment]
I just tried java sample app and updated java-client version to v6.1.0 for using W3C (and avoided some compile errors). 
 https://github.com/appium-boneyard/sample-code/tree/master/sample-code/examples/java/junit

As you said, the desktop also crashed in using java-client.
